version: "3.7"

services:
  postgres:
    container_name: nest-gql-discord-db
    image: bitnami/postgresql
    ports:
      - 5432:5432
    restart: allways
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=nest-gql-discord
  redis:
    container_name: "nest-gql-discord-redis"
    image: bitnami/redis
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data